name: Bot Runner

on:
  schedule:
    # اجرای اتوماتیک منظم در دقایق 0، 15، 30 و 45 هر ساعت
    - cron: '*/15 * * * *'
  workflow_dispatch: # برای فعال ماندن دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        run: python bot.py
